spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Eclassroom
    username: yohaan.dhuri
    password: sacyo@2021
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format-sql]': true

  graphql:
    graphiql:
      enabled: true


